version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" # 在项目根目录下查找 package 文件
    schedule:
      interval: "weekly" # 每周检查更新
    labels:
      - "dependencies" # 给PR添加标签
    open-pull-requests-limit: 10 # 同时最多打开 10 个更新 PR
