name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
          package-name: handwriting-frontend
          path: frontend/
  release-please-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: python
          package-name: handwriting-backend
          path: backend/

